version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - './data/postgres:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - './data/redis:/bitnami/redis'
  discourse:
    image: 'bitnami/discourse:latest'
    ports:
      - '82:3000'
    volumes:
      - '.data/discourse:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - '.data/sidekiq:/bitnami/discourse-sidekiq'
    command: 'nami start --foreground discourse-sidekiq'